#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.15kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/cnstark/pytorch:1.12.1-py3.9.1-cuda11.3.1-runtime-ubuntu20.04
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 116B done
#3 DONE 0.0s

#4 [ 1/10] FROM docker.io/cnstark/pytorch:1.12.1-py3.9.1-cuda11.3.1-runtime-ubuntu20.04
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 78B done
#5 DONE 0.0s

#6 [ 6/10] RUN apt update && apt install -y cmake
#6 CACHED

#7 [ 4/10] COPY conda_environment.txt conda_environment.txt
#7 CACHED

#8 [ 2/10] RUN apt update && apt install --no-install-recommends -y libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
#8 CACHED

#9 [ 7/10] RUN apt-get clean     && rm -rf /var/lib/apt/lists/*
#9 CACHED

#10 [ 8/10] RUN pip install -r conda_environment.txt
#10 CACHED

#11 [ 5/10] COPY requirments.txt requirments.txt
#11 CACHED

#12 [ 3/10] RUN apt-get clean     && rm -rf /var/lib/apt/lists/*
#12 CACHED

#13 [ 9/10] RUN pip install -r requirments.txt
#13 CACHED

#14 [10/10] RUN pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1121/download.html
#14 0.608 Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1121/download.html
#14 15.69 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='dl.fbaipublicfiles.com', port=443): Read timed out. (read timeout=15)")': /pytorch3d/packaging/wheels/py39_cu113_pyt1121/download.html
#14 20.99 Collecting pytorch3d
#14 21.23   Downloading https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1121/pytorch3d-0.7.2-cp39-cp39-linux_x86_64.whl (20.2 MB)
#14 29.89      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.2/20.2 MB 2.4 MB/s eta 0:00:00
#14 29.92 Requirement already satisfied: fvcore in /usr/local/lib/python3.9/site-packages (from pytorch3d) (0.1.5.post20221221)
#14 29.92 Requirement already satisfied: iopath in /usr/local/lib/python3.9/site-packages (from pytorch3d) (0.1.10)
#14 29.93 Requirement already satisfied: numpy in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (1.23.3)
#14 29.93 Requirement already satisfied: yacs>=0.1.6 in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (0.1.8)
#14 29.93 Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (6.0.1)
#14 29.93 Requirement already satisfied: tqdm in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (4.64.1)
#14 29.93 Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (2.0.1)
#14 29.93 Requirement already satisfied: Pillow in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (10.3.0)
#14 29.93 Requirement already satisfied: tabulate in /usr/local/lib/python3.9/site-packages (from fvcore->pytorch3d) (0.9.0)
#14 29.93 Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/site-packages (from iopath->pytorch3d) (4.11.0)
#14 29.93 Requirement already satisfied: portalocker in /usr/local/lib/python3.9/site-packages (from iopath->pytorch3d) (2.8.2)
#14 31.17 Installing collected packages: pytorch3d
#14 31.72 Successfully installed pytorch3d-0.7.2
#14 31.72 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#14 DONE 31.8s

#15 exporting to image
#15 exporting layers 0.1s done
#15 writing image sha256:ebea0af3e60c2c89149fdddeccdfa549cb499bd075cf524295a33ddb4a17f649 done
#15 naming to docker.io/jincheng_jcs/diffusion_policy:0.1.0 done
#15 DONE 0.2s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
